//-------------------------------------------------------
// Autogenerated from 'train.vmf'
//-------------------------------------------------------
LvObj <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.unnamed,
			EntityGroup.SpawnTables.survival_props,
			EntityGroup.SpawnTables.unnamed1,
			EntityGroup.SpawnTables.unnamed2,
			EntityGroup.SpawnTables.unnamed3,
			EntityGroup.SpawnTables.unnamed4,
			//EntityGroup.SpawnTables.battery_light,
			EntityGroup.SpawnTables.unnamed7,
			EntityGroup.SpawnTables.unnamed8,
			EntityGroup.SpawnTables.unnamed9,
			//EntityGroup.SpawnTables.inlight,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.unnamed9,
			EntityGroup.SpawnTables.unnamed8,
			EntityGroup.SpawnTables.unnamed7,
			//EntityGroup.SpawnTables.battery_light,
			EntityGroup.SpawnTables.unnamed4,
			EntityGroup.SpawnTables.unnamed3,
			EntityGroup.SpawnTables.unnamed2,
			EntityGroup.SpawnTables.unnamed1,
			EntityGroup.SpawnTables.unnamed,
			EntityGroup.SpawnTables.survival_props,
			//EntityGroup.SpawnTables.inlight,
			EntityGroup.SpawnTables.blockbottom,
			EntityGroup.SpawnTables.blockbottom1,//진입구
			EntityGroup.SpawnTables.blockbottom2,
			EntityGroup.SpawnTables.blockbottom3,//앞
			EntityGroup.SpawnTables.blockbottom4,
			EntityGroup.SpawnTables.blockbottom5,//뒤
			EntityGroup.SpawnTables.blockbottom6,
			EntityGroup.SpawnTables.blockbottom7,//측면
			EntityGroup.SpawnTables.blockbottom8,
			EntityGroup.SpawnTables.blockbottom9,
			EntityGroup.SpawnTables.blockbottom10,
			EntityGroup.SpawnTables.blockwallfront
			EntityGroup.SpawnTables.blockwallback
			EntityGroup.SpawnTables.blockwall0
			EntityGroup.SpawnTables.blockwall1
			EntityGroup.SpawnTables.blockwall2
			EntityGroup.SpawnTables.blockwall3
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			unnamed = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					disableselfshadowing = "0"
					disableshadows = "0"
					disablevertexlighting = "0"
					disableX360 = "0"
					fademaxdist = "3500"
					fademindist = "3000"
					fadescale = "1"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props_vehicles/train_boxcar_shell01.mdl"
					renderamt = "255"
					rendercolor = "113 139 159"
					screenspacefade = "0"
					skin = "0"
					solid = "6"
					disableshadows = true
					origin = Vector( -9.53674e-007, 1.90735e-006, 0 )
					targetname = "Level_Train"
				}
			}
			survival_props = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 359, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "1"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props_vehicles/train_boxcar_shell_door_01.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "134 145 174"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "0"
					targetname = "survival_props"
					updatechildren = "0"
					disableshadows = true
					origin = Vector( 2.42012, 77.4849, -0.39106 )
					parentname = "Level_Train"
				}
			}
			unnamed1 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 175, 0 )
					disableselfshadowing = "1"
					disableshadows = "1"
					disablevertexlighting = "0"
					disableX360 = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props_vehicles/train_boxcar_shell_door_01.mdl"
					renderamt = "255"
					rendercolor = "134 145 174"
					screenspacefade = "0"
					skin = "0"
					solid = "6"
					disableshadows = true
					origin = Vector( -3.75898, -80.1713, 0.84602 )
					parentname = "Level_Train"
				}
			}
			unnamed2 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 150.5, 0 )
					disableselfshadowing = "1"
					disableshadows = "0"
					disablevertexlighting = "0"
					disableX360 = "0"
					fademaxdist = "800"
					fademindist = "600"
					fadescale = "1"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props_equipment/sleeping_bag2.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					screenspacefade = "0"
					skin = "0"
					solid = "0"
					disableshadows = true
					origin = Vector( -0.738003, -179.891, 48.2625 )
					parentname = "Level_Train"
				}
			}
			unnamed3 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 188, 0 )
					disableselfshadowing = "1"
					disableshadows = "0"
					disablevertexlighting = "0"
					disableX360 = "0"
					fademaxdist = "800"
					fademindist = "600"
					fadescale = "1"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props_junk/food_pile03.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					screenspacefade = "0"
					skin = "0"
					solid = "0"
					disableshadows = true
					origin = Vector( -14.7514, -122.6824, 47.2625 )
					parentname = "Level_Train"
				}
			}
			unnamed4 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 270.5, 78 )
					disableselfshadowing = "1"
					disableshadows = "0"
					disablevertexlighting = "0"
					disableX360 = "0"
					fademaxdist = "1800"
					fademindist = "1600"
					fadescale = "1"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props_highway/plywood_01.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					screenspacefade = "0"
					skin = "0"
					solid = "6"
					disableshadows = true
					origin = Vector( 53.3674, -122.947, 48.2625 )
					parentname = "Level_Train"
				}
			}
			battery_light = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 176, 0 )
					disableselfshadowing = "1"
					disableshadows = "0"
					disablevertexlighting = "1"
					disableX360 = "0"
					fademaxdist = "1000"
					fademindist = "800"
					fadescale = "1"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props_lighting/light_battery_rigged_01.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					screenspacefade = "0"
					skin = "0"
					solid = "0"
					disableshadows = true
					origin = Vector( 41.9794, -80.4461, 48.2625 )
					parentname = "Level_Train"
				}
			}
			inlight = 
			{
				SpawnInfo =
				{
					classname = "light_dynamic"
					_castentityshadow = "1"
					distance = "200"
					_constant_attn = "2000"
					_fifty_percent_distance = "0"
					_hardfalloff = "0"
					_light = "253 255 217 20"
					_lightHDR = "-1 -1 -1 1"
					_lightscaleHDR = "0.5"
					_linear_attn = "0"
					_quadratic_attn = "1"
					_shadoworiginoffset = "0 0 0"
					_zero_percent_distance = "0"
					spawnflags = "0"
					style = "6"
					brightness = "1"
					origin = Vector( 33.4755, -79.6189, 80.2625 )
					parentname = "Level_Train"
				}
			}
			unnamed7 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 182.5, 0 )
					disableselfshadowing = "1"
					disableshadows = "0"
					disablevertexlighting = "0"
					disableX360 = "0"
					fademaxdist = "800"
					fademindist = "600"
					fadescale = "1"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props_junk/garbage256_composite002a.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					screenspacefade = "0"
					skin = "0"
					solid = "0"
					disableshadows = true
					origin = Vector( -0.952379, -46.823, 51.2625 )
					parentname = "Level_Train"
				}
			}
			unnamed8 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					disableselfshadowing = "0"
					disableshadows = "0"
					disablevertexlighting = "0"
					disableX360 = "0"
					fademaxdist = "3500"
					fademindist = "3000"
					fadescale = "1"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props_vehicles/train_boxcar_interior01.mdl"
					renderamt = "255"
					rendercolor = "113 139 159"
					screenspacefade = "0"
					skin = "0"
					solid = "6"
					disableshadows = true
					origin = Vector( -9.53674e-007, 1.90735e-006, 0 )
					parentname = "Level_Train"
				}
			}
			unnamed9 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 220, 0 )
					disableselfshadowing = "1"
					disableshadows = "0"
					disablevertexlighting = "0"
					disableX360 = "0"
					fademaxdist = "800"
					fademindist = "600"
					fadescale = "1"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props_equipment/sleeping_bag1.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					screenspacefade = "0"
					skin = "0"
					solid = "0"
					disableshadows = true
					origin = Vector( 5.80327, 145.649, 50.0674 )
					parentname = "Level_Train"
				}
			}
			blockbottom1 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					model = "models/props_street/police_barricade3.mdl"
					solid = "6"
					rendermode = "1"
					renderamt = "0"
					origin = Vector( 64, 0, -72 )
					angles = Vector( 0, 0, 0 )
					targetName = "Level_Train_blockbottom"
					parentname = "Level_Train"
				}
			}
			blockbottom2 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					model = "models/props_street/police_barricade3.mdl"
					solid = "6"
					rendermode = "1"
					renderamt = "0"
					origin = Vector( -64, 0, -72 )
					angles = Vector( 0, 0, 0 )
					targetName = "Level_Train_blockbottom"
					parentname = "Level_Train"
				}
			}
			blockbottom3 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					model = "models/props_street/police_barricade.mdl"
					solid = "6"
					rendermode = "1"
					renderamt = "0"
					origin = Vector( 40, 265, -72 )
					angles = Vector( 0, 90, 0 )
					targetName = "Level_Train_blockbottom"
					parentname = "Level_Train"
				}
			}
			blockbottom4 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					model = "models/props_street/police_barricade.mdl"
					solid = "6"
					rendermode = "1"
					renderamt = "0"
					origin = Vector( -40, 265, -72 )
					angles = Vector( 0, 90, 0 )
					targetName = "Level_Train_blockbottom"
					parentname = "Level_Train"
				}
			}
			blockbottom5 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					model = "models/props_street/police_barricade.mdl"
					solid = "6"
					rendermode = "1"
					renderamt = "0"
					origin = Vector( 40, -265, -72 )
					angles = Vector( 0, 90, 0 )
					targetName = "Level_Train_blockbottom"
					parentname = "Level_Train"
				}
			}
			blockbottom6 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					model = "models/props_street/police_barricade.mdl"
					solid = "6"
					rendermode = "1"
					renderamt = "0"
					origin = Vector( -40, -265, -72 )
					angles = Vector( 0, 90, 0 )
					targetName = "Level_Train_blockbottom"
					parentname = "Level_Train"
				}
			}
			blockbottom7 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					model = "models/props_street/police_barricade2.mdl"
					solid = "6"
					rendermode = "1"
					renderamt = "0"
					origin = Vector( -60, 185, -22 )
					angles = Vector( 0, 0, 0 )
					targetName = "Level_Train_blockbottom"
					parentname = "Level_Train"
				}
			}
			blockbottom8 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					model = "models/props_street/police_barricade2.mdl"
					solid = "6"
					rendermode = "1"
					renderamt = "0"
					origin = Vector( -60, -185, -22 )
					angles = Vector( 0, 0, 0 )
					targetName = "Level_Train_blockbottom"
					parentname = "Level_Train"
				}
			}
			blockbottom9 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					model = "models/props_street/police_barricade2.mdl"
					solid = "6"
					rendermode = "1"
					renderamt = "0"
					origin = Vector( 60, 185, -22 )
					angles = Vector( 0, 0, 0 )
					targetName = "Level_Train_blockbottom"
					parentname = "Level_Train"
				}
			}
			blockbottom10 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					model = "models/props_street/police_barricade2.mdl"
					solid = "6"
					rendermode = "1"
					renderamt = "0"
					origin = Vector( 60, -185, -22 )
					angles = Vector( 0, 0, 0 )
					targetName = "Level_Train_blockbottom"
					parentname = "Level_Train"
				}
			}
			blockbottom = 
			{
				SpawnInfo =
				{
					classname = "env_physics_blocker"
					origin = Vector( 0, 0, -10 )
					angles = Vector( 0, 0, 0 )
					mins = Vector( -58, -256, -100 )
					boxmins = Vector( -58, -256, -100 )
					maxs = Vector( 58, 256, 57 )
					boxmaxs = Vector( 58, 256, 57 )
					initialstate = "1"
					BlockType = "4"
					targetName = "Level_Train_blockbottom"
					//parentname = "Level_Train"
				}
			}
			blockwallfront = 
			{
				SpawnInfo =
				{
					classname = "env_physics_blocker"
					origin = Vector( 0, 254, 30 )
					angles = Vector( 0, 0, 0 )
					mins = Vector( -58, -1, 0 )
					boxmins = Vector( -58, -1, 0 )
					maxs = Vector( 58, 1, 200 )
					boxmaxs = Vector( 58, 1, 200 )
					initialstate = "1"
					BlockType = "4"
					targetName = "Level_Train_block"
					//parentname = "Level_Train"
				}
			}
			blockwallback = 
			{
				SpawnInfo =
				{
					classname = "env_physics_blocker"
					origin = Vector( 0, -254, 30 )
					angles = Vector( 0, 0, 0 )
					mins = Vector( -58, -1, 0 )
					boxmins = Vector( -58, -1, 0 )
					maxs = Vector( 58, 1, 200 )
					boxmaxs = Vector( 58, 1, 200 )
					initialstate = "1"
					BlockType = "4"
					targetName = "Level_Train_block"
					//parentname = "Level_Train"
				}
			}
			/*
			blockwall0 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					model = "models/props_street/police_barricade2.mdl"
					solid = "6"
					//rendermode = "1"
					//renderamt = "0"
					origin = Vector( 62, 150, -10 )
					angles = Vector( 0, 0, 0 )
					targetName = "Level_Train_blockbottomL"
					parentname = "Level_Train"
				}
			}
			blockwall1 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					model = "models/props_street/police_barricade2.mdl"
					solid = "6"
					//rendermode = "1"
					//renderamt = "0"
					origin = Vector( 62, -150, -10 )
					angles = Vector( 0, 0, 0 )
					targetName = "Level_Train_blockbottomL"
					parentname = "Level_Train"
				}
			}
			*/
			blockwall0 = 
			{
				SpawnInfo =
				{
					classname = "env_physics_blocker"
					origin = Vector( 60, 156, 30 )
					angles = Vector( 0, 0, 0 )
					mins = Vector( -1, -108, 0 )
					boxmins = Vector( -1, -108, 0 )
					maxs = Vector( 1, 108, 200 )
					boxmaxs = Vector( 1, 108, 200 )
					initialstate = "1"
					BlockType = "4"
					targetName = "Level_Train_block"
					//parentname = "Level_Train"
				}
			}
			blockwall1 = 
			{
				SpawnInfo =
				{
					classname = "env_physics_blocker"
					origin = Vector( 60, -156, 30 )
					angles = Vector( 0, 0, 0 )
					mins = Vector( -1, -108, 0 )
					boxmins = Vector( -1, -108, 0 )
					maxs = Vector( 1, 108, 200 )
					boxmaxs = Vector( 1, 108, 200 )
					initialstate = "1"
					BlockType = "4"
					targetName = "Level_Train_block"
					//parentname = "Level_Train"
				}
			}
			blockwall2 = 
			{
				SpawnInfo =
				{
					classname = "env_physics_blocker"
					origin = Vector( -60, 156, 30 )
					angles = Vector( 0, 0, 0 )
					mins = Vector( -1, -108, 0 )
					boxmins = Vector( -1, -108, 0 )
					maxs = Vector( 1, 108, 200 )
					boxmaxs = Vector( 1, 108, 200 )
					initialstate = "1"
					BlockType = "4"
					targetName = "Level_Train_block"
					//parentname = "Level_Train"
				}
			}
			blockwall3 = 
			{
				SpawnInfo =
				{
					classname = "env_physics_blocker"
					origin = Vector( -60, -156, 30 )
					angles = Vector( 0, 0, 0 )
					mins = Vector( -1, -108, 0 )
					boxmins = Vector( -1, -108, 0 )
					maxs = Vector( 1, 108, 200 )
					boxmaxs = Vector( 1, 108, 200 )
					initialstate = "1"
					BlockType = "4"
					targetName = "Level_Train_block"
					//parentname = "Level_Train"
				}
			}
		} // SpawnTables
	} // EntityGroup
} // Train

RegisterEntityGroup( "LvObj", LvObj )