//-------------------------------------------------------
// Autogenerated from 'table.vmf'
//-------------------------------------------------------
LvObj <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.controlroom_desk001b,

		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.origin,
			EntityGroup.SpawnTables.controlroom_desk001b,
			EntityGroup.SpawnTables.block0,
			EntityGroup.SpawnTables.block1,
			EntityGroup.SpawnTables.block2,
			EntityGroup.SpawnTables.block3,
			EntityGroup.SpawnTables.block4,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			origin =
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					parentname = "Level_controlroom_desk001b"
					angles = Vector( 0, 0, 0 )
					model = "models/brokenglass_piece.mdl"
					renderamt = "0"
					rendercolor = "0 0 0"
					rendermode = "1"
					origin = Vector( 0, 0, 0 )
					targetname = "Level_origin"
				}
			}
			block0 =
			{//상판
				SpawnInfo =
				{
					classname = "env_physics_blocker"
					targetname = "Level_block"
					parentname = "Level_controlroom_desk001b"
					mins = Vector( -20.6, -55.5, 30 )
					boxmins = Vector( -20.6, -55.5, 30 )
					maxs = Vector( 20.6, 55.5, 33.4 )
					boxmaxs = Vector( 20.6, 55.5, 33.4 )
					initialstate = "1"
					BlockType = "4"
					origin = Vector( 0, 0, 0 )
				}
			}
			block1 =
			{//앞판
				SpawnInfo =
				{
					classname = "env_physics_blocker"
					targetname = "Level_block"
					parentname = "Level_controlroom_desk001b"
					mins = Vector( 17.5, -53.6, 0 )
					boxmins = Vector( 17.5, -53.6, 0 )
					maxs = Vector( 20.6, 53.6, 30 )
					boxmaxs = Vector( 20.6, 53.6, 30 )
					initialstate = "1"
					BlockType = "4"
					origin = Vector( 0, 0, 0 )
				}
			}
			block2 =
			{//다리1
				SpawnInfo =
				{
					classname = "env_physics_blocker"
					targetname = "Level_block"
					parentname = "Level_controlroom_desk001b"
					mins = Vector( -16.2, -53.6, 0 )
					boxmins = Vector( -16.2, -53.6, 0 )
					maxs = Vector( -18.4, -50, 30 )
					boxmaxs = Vector( -18.4, -50, 30 )
					initialstate = "1"
					BlockType = "4"
					origin = Vector( 0, 0, 0 )
				}
			}
			block3 =
			{//다리2
				SpawnInfo =
				{
					classname = "env_physics_blocker"
					targetname = "Level_block"
					parentname = "Level_controlroom_desk001b"
					mins = Vector( -16.2, 50, 0 )
					boxmins = Vector( -16.2, 50, 0 )
					maxs = Vector( -18.4, 53.6, 30 )
					boxmaxs = Vector( -18.4, 53.6, 30 )
					initialstate = "1"
					BlockType = "4"
					origin = Vector( 0, 0, 0 )
				}
			}
			block4 =
			{//서랍
				SpawnInfo =
				{
					classname = "env_physics_blocker"
					targetname = "Level_block"
					parentname = "Level_controlroom_desk001b"
					mins = Vector( -18.9, -38.4, 24.2 )
					boxmins = Vector( -18.9, -38.4, 24.2 )
					maxs = Vector( 4.6, 38.4, 30 )
					boxmaxs = Vector( 4.6, 38.4, 30 )
					initialstate = "1"
					BlockType = "4"
					origin = Vector( 0, 0, 0 )
				}
			}
			controlroom_desk001b = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					targetname = "Level_controlroom_desk001b"
					disableshadows = "1"
					angles = Vector( 0, 180, 0 )
					body = "0"
					disablereceiveshadows = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_wasteland/controlroom_desk001b.mdl"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					solid = "6"
					spawnflags = "0"
					origin = Vector( 0, 0, 16.6 )
				}
			}
		} // SpawnTables
	} // EntityGroup
} // Table

RegisterEntityGroup( "LvObj", LvObj )