//-------------------------------------------------------
// Autogenerated from 'trainladder.vmf'
//-------------------------------------------------------
LvObj <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.Level_ladder,
			EntityGroup.SpawnTables.Level_obj,
			EntityGroup.SpawnTables.Level_worldOut,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.Level_obj,
			EntityGroup.SpawnTables.Level_glass,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			Level_obj = 
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					model = "models/props_exteriors/guardshack.mdl"
					disableshadows = "1"
					targetname = "Level_obj"
					origin = Vector( 0, 0, 0 )
					spawnflags = "264"
					solid = "6"
					rendercolor = "160 160 160"
					damagefilter = "filter_tank"
					BreakableType = "2"
					connections =
					{
						OnHealthChanged =
						{
							cmd1 = "Level_objBreak0-1"
						}
					}
				}
			}
			Level_glass = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					model = "models/props_exteriors/guardshack_glass.mdl"
					disableshadows = "1"
					targetname = "Level_glass"
					parentname = "Level_obj"
					origin = Vector( 0, 0, 0 )
					spawnflags = "0"
				}
			}
		} // SpawnTables
	} // EntityGroup
} // Trainladder

RegisterEntityGroup( "LvObj", LvObj )