//-------------------------------------------------------
// Autogenerated from 'subways.vmf'
//-------------------------------------------------------
LvObj <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.unnamed,
			EntityGroup.SpawnTables.unnamed1,
			EntityGroup.SpawnTables.unnamed2,
			EntityGroup.SpawnTables.unnamed3,
			EntityGroup.SpawnTables.unnamed19,
			EntityGroup.SpawnTables.unnamed20,
			EntityGroup.SpawnTables.unnamed21,
			EntityGroup.SpawnTables.unnamed22,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.unnamed22,
			EntityGroup.SpawnTables.unnamed21,
			EntityGroup.SpawnTables.unnamed20,
			EntityGroup.SpawnTables.unnamed19,
			EntityGroup.SpawnTables.unnamed18,
			EntityGroup.SpawnTables.unnamed16,
			EntityGroup.SpawnTables.unnamed15,
			EntityGroup.SpawnTables.unnamed14,
			EntityGroup.SpawnTables.unnamed11,
			EntityGroup.SpawnTables.unnamed7,
			EntityGroup.SpawnTables.unnamed3,
			EntityGroup.SpawnTables.unnamed2,
			EntityGroup.SpawnTables.unnamed1,
			EntityGroup.SpawnTables.unnamed,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			unnamed = 
			{
				SpawnInfo =
				{
					classname = "env_sprite"
					disablereceiveshadows = "0"
					fademindist = "-1"
					fadescale = "1"
					framerate = "10.0"
					GlowProxySize = "6"
					HDRColorScale = ".5"
					model = "sprites/redglow3.vmt"
					renderamt = "200"
					rendercolor = "255 5 5"
					renderfx = "0"
					rendermode = "9"
					scale = ".45"
					spawnflags = "1"
					origin = Vector( -244.326, 37.7158, 60.016 )
					parentname = "Level_SuvwayOpen_car1"
				}
			}
			unnamed1 = 
			{
				SpawnInfo =
				{
					classname = "env_sprite"
					disablereceiveshadows = "0"
					fademindist = "-1"
					fadescale = "1"
					framerate = "10.0"
					GlowProxySize = "6"
					HDRColorScale = ".5"
					model = "sprites/redglow3.vmt"
					renderamt = "200"
					rendercolor = "255 5 5"
					renderfx = "0"
					rendermode = "9"
					scale = ".45"
					spawnflags = "1"
					origin = Vector( -235.93, 49.1006, 60.083 )
					parentname = "Level_SuvwayOpen_car1"
				}
			}
			unnamed2 = 
			{
				SpawnInfo =
				{
					classname = "env_sprite"
					disablereceiveshadows = "0"
					fademindist = "-1"
					fadescale = "1"
					framerate = "10.0"
					GlowProxySize = "6"
					HDRColorScale = ".5"
					model = "sprites/redglow3.vmt"
					renderamt = "200"
					rendercolor = "255 5 5"
					renderfx = "0"
					rendermode = "9"
					scale = ".45"
					spawnflags = "1"
					origin = Vector( -244.23, -37.8984, 60.421 )
					parentname = "Level_SuvwayOpen_car1"
				}
			}
			unnamed3 = 
			{
				SpawnInfo =
				{
					classname = "env_sprite"
					disablereceiveshadows = "0"
					fademindist = "-1"
					fadescale = "1"
					framerate = "10.0"
					GlowProxySize = "6"
					HDRColorScale = ".5"
					model = "sprites/redglow3.vmt"
					renderamt = "200"
					rendercolor = "255 5 5"
					renderfx = "0"
					rendermode = "9"
					scale = ".45"
					spawnflags = "1"
					origin = Vector( -235.06, -48.5249, 59.907 )
					parentname = "Level_SuvwayOpen_car1"
				}
			}
			unnamed8 = 
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					solid = "2"
					angles = Vector( 0, 0, 0 )
					body = "0"
					BreakableType = "2"
					damagetoenablemotion = "0"
					Damagetype = "0"
					disablereceiveshadows = "0"
					disableshadows = "1"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "1536"
					fademindist = "1024"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					inertiaScale = "1.0"
					massScale = "0"
					minhealthdmg = "0"
					model = "models/props_unique/subwaycar_all_onetexture_sidedoorb.mdl"
					nodamageforces = "0"
					PerformanceMode = "0"
					physdamagescale = "0.1"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					shadowcastdist = "0"
					skin = "0"
					spawnflags = "266"
					origin = Vector( -80, 50, 82 )
					parentname = "Level_SuvwayOpen_car1"
					connections =
					{
						OnBreak =
						{
							cmd1 = "tankwindow02Break0-1"
						}
					}
				}
			}
			unnamed10 = 
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					solid = "6"
					angles = Vector( 0, 0, 0 )
					body = "0"
					BreakableType = "2"
					damagetoenablemotion = "0"
					Damagetype = "0"
					disablereceiveshadows = "0"
					disableshadows = "1"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "1536"
					fademindist = "1024"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					inertiaScale = "1.0"
					massScale = "0"
					minhealthdmg = "0"
					model = "models/props_unique/subwaycar_all_onetexture_sidedoorb.mdl"
					nodamageforces = "0"
					PerformanceMode = "0"
					physdamagescale = "0.1"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					shadowcastdist = "0"
					skin = "0"
					spawnflags = "266"
					origin = Vector( 80, 50, 82 )
					parentname = "Level_SuvwayOpen_car1"
					connections =
					{
						OnBreak =
						{
							cmd1 = "tankwindow08Break0-1"
						}
					}
				}
			}
			unnamed102 = 
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					solid = "6"
					angles = Vector( 0, 0, 0 )
					body = "0"
					BreakableType = "2"
					damagetoenablemotion = "0"
					Damagetype = "0"
					disablereceiveshadows = "0"
					disableshadows = "1"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "1536"
					fademindist = "1024"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					inertiaScale = "1.0"
					massScale = "0"
					minhealthdmg = "0"
					model = "models/props_unique/subwaycar_all_onetexture_sidedoorb.mdl"
					nodamageforces = "0"
					PerformanceMode = "0"
					physdamagescale = "0.1"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					shadowcastdist = "0"
					skin = "0"
					spawnflags = "266"
					origin = Vector( 80, -50, 82 )
					parentname = "Level_SuvwayOpen_car1"
					connections =
					{
						OnBreak =
						{
							cmd1 = "tankwindow08Break0-1"
						}
					}
				}
			}
			unnamed11 = 
			{
				SpawnInfo =
				{
					classname = "func_breakable"
					disablereceiveshadows = "0"
					disableshadows = "0"
					ExplodeDamage = "0"
					explodemagnitude = "0"
					ExplodeRadius = "0"
					explosion = "0"
					fademindist = "-1"
					fadescale = "1"
					gibdir = "0 0 0"
					health = "1"
					material = "0"
					minhealthdmg = "0"
					nodamageforces = "0"
					origin = Vector( 196.72, 51.32, 101.23 )
					PerformanceMode = "0"
					physdamagescale = "1.0"
					pressuredelay = "0"
					propdata = "24"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					spawnobject = "0"
				}
			}
			unnamed13 = 
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					solid = "6"
					angles = Vector( 0, 0, 0 )
					body = "0"
					BreakableType = "2"
					damagetoenablemotion = "0"
					Damagetype = "0"
					disablereceiveshadows = "0"
					disableshadows = "1"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademindist = "-1"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					inertiaScale = "1.0"
					massScale = "0"
					minhealthdmg = "0"
					model = "models/props_unique/subwaycar_all_onetexture_enddoorb.mdl"
					nodamageforces = "0"
					PerformanceMode = "0"
					physdamagescale = "0.1"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					shadowcastdist = "0"
					skin = "0"
					spawnflags = "266"
					origin = Vector( 227.396, 0, 82 )
					parentname = "Level_SuvwayOpen_car1"
					connections =
					{
						OnBreak =
						{
							cmd1 = "tankwindow09Break0-1"
						}
					}
				}
			}
			unnamed132 = 
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					solid = "6"
					angles = Vector( 0, 180, 0 )
					body = "0"
					BreakableType = "2"
					damagetoenablemotion = "0"
					Damagetype = "0"
					disablereceiveshadows = "0"
					disableshadows = "1"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademindist = "-1"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					inertiaScale = "1.0"
					massScale = "0"
					minhealthdmg = "0"
					model = "models/props_unique/subwaycar_all_onetexture_enddoorb.mdl"
					nodamageforces = "0"
					PerformanceMode = "0"
					physdamagescale = "0.1"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					shadowcastdist = "0"
					skin = "0"
					spawnflags = "266"
					origin = Vector( -227.396, 0, 82 )
					parentname = "Level_SuvwayOpen_car1"
					connections =
					{
						OnBreak =
						{
							cmd1 = "tankwindow09Break0-1"
						}
					}
				}
			}
			unnamed14 = 
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					disableshadows = "1"
					origin = Vector( 220, -51, 30 )
					angles = Vector( 0, -90, 0 )
					model = "models/props_windows/hotel_window_glass002.mdl"
					spawnflags = "264"
					renderamt = "220"
					rendercolor = "255 255 255"
					parentname = "Level_SuvwayOpen_car1"
				}
			}
			unnamed15 = 
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					disableshadows = "1"
					origin = Vector( 50, -51, 130 )
					angles = Vector( 0, -90, 90 )
					model = "models/props_windows/hotel_window_glass001.mdl"
					spawnflags = "264"
					renderamt = "255"
					rendercolor = "255 255 255"
					parentname = "Level_SuvwayOpen_car1"
				}
			}
			unnamed16 = 
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					disableshadows = "1"
					origin = Vector( -220, -51, 30 )
					angles = Vector( 0, 90, 0 )
					model = "models/props_windows/hotel_window_glass002.mdl"
					spawnflags = "264"
					renderamt = "255"
					rendercolor = "255 255 255"
					parentname = "Level_SuvwayOpen_car1"
				}
			}
			unnamed11 = 
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					disableshadows = "1"
					origin = Vector( 160, 51, 30 )
					angles = Vector( 0, 90, 0 )
					model = "models/props_windows/hotel_window_glass002.mdl"
					spawnflags = "264"
					renderamt = "255"
					rendercolor = "255 255 255"
					parentname = "Level_SuvwayOpen_car1"
				}
			}
			unnamed18 = 
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					disableshadows = "1"
					origin = Vector( 50, 51, 130 )
					angles = Vector( 0, -90, 90 )
					model = "models/props_windows/hotel_window_glass003.mdl"
					spawnflags = "264"
					renderamt = "255"
					rendercolor = "255 255 255"
					parentname = "Level_SuvwayOpen_car1"
				}
			}
			unnamed7 = 
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					disableshadows = "1"
					origin = Vector( -160, 51, 45 )
					angles = Vector( 0, -90, 0 )
					model = "models/props_windows/hotel_window_glass003.mdl"
					spawnflags = "264"
					renderamt = "255"
					rendercolor = "255 255 255"
					parentname = "Level_SuvwayOpen_car1"
				}
			}
			unnamed19 = 
			{
				SpawnInfo =
				{
					classname = "env_sprite"
					disablereceiveshadows = "0"
					fademindist = "-1"
					fadescale = "1"
					framerate = "10.0"
					GlowProxySize = "6"
					HDRColorScale = ".5"
					model = "sprites/redglow3.vmt"
					renderamt = "200"
					rendercolor = "255 5 5"
					renderfx = "0"
					rendermode = "9"
					scale = ".45"
					spawnflags = "1"
					origin = Vector( 245.018, -37.9287, 60.016 )
					parentname = "Level_SuvwayOpen_car1"
				}
			}
			unnamed20 = 
			{
				SpawnInfo =
				{
					classname = "env_sprite"
					disablereceiveshadows = "0"
					fademindist = "-1"
					fadescale = "1"
					framerate = "10.0"
					GlowProxySize = "6"
					HDRColorScale = ".5"
					model = "sprites/redglow3.vmt"
					renderamt = "200"
					rendercolor = "255 5 5"
					renderfx = "0"
					rendermode = "9"
					scale = ".45"
					spawnflags = "1"
					origin = Vector( 236.622, -49.3135, 60.083 )
					parentname = "Level_SuvwayOpen_car1"
				}
			}
			unnamed21 = 
			{
				SpawnInfo =
				{
					classname = "env_sprite"
					disablereceiveshadows = "0"
					fademindist = "-1"
					fadescale = "1"
					framerate = "10.0"
					GlowProxySize = "6"
					HDRColorScale = ".5"
					model = "sprites/redglow3.vmt"
					renderamt = "200"
					rendercolor = "255 5 5"
					renderfx = "0"
					rendermode = "9"
					scale = ".45"
					spawnflags = "1"
					origin = Vector( 246.165, 38.4297, 60.421 )
					parentname = "Level_SuvwayOpen_car1"
				}
			}
			unnamed22 = 
			{
				SpawnInfo =
				{
					classname = "env_sprite"
					disablereceiveshadows = "0"
					fademindist = "-1"
					fadescale = "1"
					framerate = "10.0"
					GlowProxySize = "6"
					HDRColorScale = ".5"
					model = "sprites/redglow3.vmt"
					renderamt = "200"
					rendercolor = "255 5 5"
					renderfx = "0"
					rendermode = "9"
					scale = ".45"
					spawnflags = "1"
					origin = Vector( 236.996, 49.0567, 59.907 )
					parentname = "Level_SuvwayOpen_car1"
				}
			}
		} // SpawnTables
	} // EntityGroup
} // Subways

RegisterEntityGroup( "LvObj", LvObj )