//-------------------------------------------------------
// Autogenerated from 'table.vmf'
//-------------------------------------------------------
LvObj <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.hotel_rooftop_equip001,

		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.hotel_rooftop_equip001,
			EntityGroup.SpawnTables.block0,
			EntityGroup.SpawnTables.block1,
			EntityGroup.SpawnTables.block2,
			EntityGroup.SpawnTables.block3,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			
			block0 =
			{//몸체
				SpawnInfo =
				{
					classname = "env_physics_blocker"
					targetname = "Level_block"
					parentname = "Level_hotel_rooftop_equip001"
					mins = Vector( 6.4, -98.4, 0 )
					boxmins = Vector( 6.4, -98.4, 0 )
					maxs = Vector( 82.4, 14, 72 )
					boxmaxs = Vector( 82.4, 14, 72 )
					initialstate = "1"
					BlockType = "4"
					origin = Vector( 0, 0, 0 )
				}
			}
			block1 =
			{//상판
				SpawnInfo =
				{
					classname = "env_physics_blocker"
					targetname = "Level_block"
					parentname = "Level_hotel_rooftop_equip001"
					mins = Vector( 6, -93.4, 72 )
					boxmins = Vector( 6, -93.4, 72 )
					maxs = Vector( 83, 15.7, 75 )
					boxmaxs = Vector( 83, 15.7, 75 )
					initialstate = "1"
					BlockType = "4"
					origin = Vector( 0, 0, 0 )
				}
			}
			block2 =
			{//덕트
				SpawnInfo =
				{
					classname = "env_physics_blocker"
					targetname = "Level_block"
					parentname = "Level_hotel_rooftop_equip001"
					mins = Vector( 46, 14, 25 )
					boxmins = Vector( 46, 14, 25 )
					maxs = Vector( 76.5, 56, 50.5 )
					boxmaxs = Vector( 76.5, 56, 50.5 )
					initialstate = "1"
					BlockType = "4"
					origin = Vector( 0, 0, 0 )
				}
			}
			block3 =
			{//덕트2(경사)
				SpawnInfo =
				{
					classname = "env_physics_blocker"
					targetname = "Level_block"
					parentname = "Level_hotel_rooftop_equip001"
					mins = Vector( -13, -13, 3 )
					boxmins = Vector( -13, -13, 3 )
					maxs = Vector( 13, 13, 26 )
					boxmaxs = Vector( 13, 13, 26 )
					initialstate = "1"
					BlockType = "4"
					origin = Vector( 61.5, 74.5, 40 )
					angles = Vector( 0, 0, 135)
				}
			}
			hotel_rooftop_equip001 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					targetname = "Level_hotel_rooftop_equip001"
					disableshadows = "1"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_rooftop/hotel_rooftop_equip001.mdl"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					solid = "6"
					spawnflags = "0"
					origin = Vector( 0, 0, 0 )
				}
			}
		} // SpawnTables
	} // EntityGroup
} // Table

RegisterEntityGroup( "LvObj", LvObj )