//-------------------------------------------------------
// Autogenerated from 'table.vmf'
//-------------------------------------------------------
LvObj <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.bookcasehutch01,

		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.bookcasehutch01,
			EntityGroup.SpawnTables.block0,
			EntityGroup.SpawnTables.block1,
			EntityGroup.SpawnTables.block2,
			EntityGroup.SpawnTables.block3,
			EntityGroup.SpawnTables.block4,
			EntityGroup.SpawnTables.block5,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			
			block0 =
			{//밑
				SpawnInfo =
				{
					classname = "env_physics_blocker"
					targetname = "Level_block"
					parentname = "Level_Bookcasehutch01"
					mins = Vector( -12.5, -24, 0 )
					boxmins = Vector( -12.5, -24, 0 )
					maxs = Vector( 12.5, 24, 36.3 )
					boxmaxs = Vector( 12.5, 24, 36.3 )
					initialstate = "1"
					BlockType = "4"
					origin = Vector( 0, 0, 0 )
				}
			}
			block1 =
			{//맨위
				SpawnInfo =
				{
					classname = "env_physics_blocker"
					targetname = "Level_block"
					parentname = "Level_Bookcasehutch01"
					mins = Vector( -8.5, -24, 85 )
					boxmins = Vector( -8.5, -24, 85 )
					maxs = Vector( 8.5, 24, 87.5 )
					boxmaxs = Vector( 8.5, 24, 87.5 )
					initialstate = "1"
					BlockType = "4"
					origin = Vector( 4, 0, 0 )
				}
			}
			block2 =
			{//2층
				SpawnInfo =
				{
					classname = "env_physics_blocker"
					targetname = "Level_block"
					parentname = "Level_Bookcasehutch01"
					mins = Vector( -8.5, -24, 67.9 )
					boxmins = Vector( -8.5, -24, 67.9 )
					maxs = Vector( 8.5, 24, 68.4 )
					boxmaxs = Vector( 8.5, 24, 68.4 )
					initialstate = "1"
					BlockType = "4"
					origin = Vector( 4, 0, 0 )
				}
			}
			block3 =
			{//1층
				SpawnInfo =
				{
					classname = "env_physics_blocker"
					targetname = "Level_block"
					parentname = "Level_Bookcasehutch01"
					mins = Vector( -8.5, -24, 51.1 )
					boxmins = Vector( -8.5, -24, 51.1 )
					maxs = Vector( 8.5, 24, 51.7 )
					boxmaxs = Vector( 8.5, 24, 51.7 )
					initialstate = "1"
					BlockType = "4"
					origin = Vector( 4, 0, 0 )
				}
			}
			block4 =
			{//옆
				SpawnInfo =
				{
					classname = "env_physics_blocker"
					targetname = "Level_block"
					parentname = "Level_Bookcasehutch01"
					mins = Vector( -8.5, -24, 0 )
					boxmins = Vector( -8.5, -24, 0 )
					maxs = Vector( 8.5, -23, 87.5 )
					boxmaxs = Vector( 8.5, -23, 87.5 )
					initialstate = "1"
					BlockType = "4"
					origin = Vector( 4, 0, 0 )
				}
			}
			block5 =
			{//옆
				SpawnInfo =
				{
					classname = "env_physics_blocker"
					targetname = "Level_block"
					parentname = "Level_Bookcasehutch01"
					mins = Vector( -8.5, 23, 0 )
					boxmins = Vector( -8.5, 23, 0 )
					maxs = Vector( 8.5, 24, 87.5 )
					boxmaxs = Vector( 8.5, 24, 87.5 )
					initialstate = "1"
					BlockType = "4"
					origin = Vector( 4, 0, 0 )
				}
			}
			bookcasehutch01 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					targetname = "Level_Bookcasehutch01"
					disableshadows = "1"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_interiors/bookcasehutch01.mdl"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					solid = "6"
					spawnflags = "0"
					origin = Vector( 0, 0, 0 )
				}
			}
		} // SpawnTables
	} // EntityGroup
} // Table

RegisterEntityGroup( "LvObj", LvObj )