//-------------------------------------------------------
// Autogenerated from 'trainladder.vmf'
//-------------------------------------------------------
LvObj <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.Level_ladder,
			EntityGroup.SpawnTables.Level_obj,
			EntityGroup.SpawnTables.Level_worldOut,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.Level_obj,
			EntityGroup.SpawnTables.Level_obj1,
			EntityGroup.SpawnTables.Level_obj2,
			EntityGroup.SpawnTables.Level_obj3,
			EntityGroup.SpawnTables.Level_pylon1,
			EntityGroup.SpawnTables.Level_pylon2,
			EntityGroup.SpawnTables.Level_pylon3,
			EntityGroup.SpawnTables.Level_pylon4,
			EntityGroup.SpawnTables.Level_glass,
			EntityGroup.SpawnTables.block,
			EntityGroup.SpawnTables.block2,
			EntityGroup.SpawnTables.block3,
			EntityGroup.SpawnTables.blockpylon1
			EntityGroup.SpawnTables.blockpylon2
			EntityGroup.SpawnTables.blockpylon3
			EntityGroup.SpawnTables.blockpylon4
			EntityGroup.SpawnTables.Level_navblock,
			EntityGroup.SpawnTables.Level_navblock1,
			EntityGroup.SpawnTables.Level_navblock2,
			EntityGroup.SpawnTables.Level_navblock3,
			EntityGroup.SpawnTables.Level_navblock4,
			EntityGroup.SpawnTables.Level_worldOut,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			Level_obj = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					model = "models/props_exteriors/guardshack.mdl"
					disableshadows = "1"
					targetname = "Level_obj"
					origin = Vector( 0, 0, 0 )
					//spawnflags = "266"
					solid = "6"
					rendercolor = "230 255 250"
					damagefilter = "filter_tank"
					BreakableType = "2"
					//connections =
					//{
						//OnHealthChanged =
						//{
						//	cmd1 = "Level_objBreak0-1"
						//}
					//}
				}
			}
			Level_glass = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					model = "models/props_exteriors/guardshack_glass.mdl"
					disableshadows = "1"
					targetname = "Level_glass"
					parentname = "Level_obj"
					origin = Vector( 0, 0, 0 )
					spawnflags = "0"
				}
			}
			Level_obj1 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					model = "models/props_cemetery/crypts_base04.mdl"
					disableshadows = "1"
					targetname = "Level_obj1"
					origin = Vector( -20, 0, -21 )
					angles = Vector( 0.5, 0, 0.1)
					solid = "6"
					rendercolor = "180 190 180"
				}
			}
			Level_obj2 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					model = "models/props_cemetery/crypts_base04.mdl"
					disableshadows = "1"
					targetname = "Level_obj2"
					origin = Vector( -0.1, 0, -21 )
					solid = "6"
					rendercolor = "180 190 180"
				}
			}
			Level_obj3 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					model = "models/props_cemetery/crypts_base04.mdl"
					disableshadows = "1"
					targetname = "Level_obj3"
					origin = Vector( 20, 0, -21 )
					angles = Vector( -0.2, 0, -0.1)
					solid = "6"
					rendercolor = "180 190 180"
				}
			}
			Level_pylon1 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					model = "models/props/cs_assault/pylon.mdl"
					disableshadows = "1"
					targetname = "Level_pylon"
					origin = Vector( 90, 40, -12 )
					angles = Vector( 0, 0, 0)
					solid = "6"
					rendercolor = "180 190 180"
				}
			}
			Level_pylon2 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					model = "models/props/cs_assault/pylon.mdl"
					disableshadows = "1"
					targetname = "Level_pylon"
					origin = Vector( -90, -40, -12 )
					angles = Vector( 0, 90, 0)
					solid = "6"
					rendercolor = "180 190 180"
				}
			}
			Level_pylon3 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					model = "models/props/cs_assault/pylon.mdl"
					disableshadows = "1"
					targetname = "Level_pylon"
					origin = Vector( -90, 40, -12 )
					angles = Vector( 0, 270, 0)
					solid = "6"
					rendercolor = "180 190 180"
				}
			}
			Level_pylon4 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					model = "models/props/cs_assault/pylon.mdl"
					disableshadows = "1"
					targetname = "Level_pylon"
					origin = Vector( 90, -40, -12 )
					angles = Vector( 0, 90, 0)
					solid = "6"
					rendercolor = "180 190 180"
				}
			}
			block =
			{
				SpawnInfo =
				{
					classname = "env_physics_blocker"
					targetname = "Level_block"
					mins = Vector( -102.5, -52, 0 )
					boxmins = Vector( -102.5, -52, 0 )
					maxs = Vector( 102.5, 52, 13 )
					boxmaxs = Vector( 102.5, 52, 13 )
					initialstate = "1"
					BlockType = "4"
					origin = Vector( 0, 0, -10 )
				}
			}
			block2 =
			{
				SpawnInfo =
				{
					classname = "env_physics_blocker"
					targetname = "Level_block"
					mins = Vector( -102.75, -52.25, 0 )
					boxmins = Vector( -102.75, -52.25, 0 )
					maxs = Vector( 102.75, 52.25, 6 )
					boxmaxs = Vector( 102.75, 52.25, 6 )
					initialstate = "1"
					BlockType = "4"
					origin = Vector( 0, 0, -10 )
				}
			}
			block3 =
			{
				SpawnInfo =
				{
					classname = "env_physics_blocker"
					targetname = "Level_block"
					mins = Vector( -46, -46, 0 )
					boxmins = Vector( -46, -46, 0 )
					maxs = Vector( 46, 46, 6 )
					boxmaxs = Vector( 46, 46, 150 )
					initialstate = "1"
					BlockType = "4"
					origin = Vector( 0, 0, 0 )
				}
			}
			blockpylon1 =
			{
				SpawnInfo =
				{
					classname = "env_physics_blocker"
					targetname = "Level_block"
					mins = Vector( -4.5, -4.5, 0 )
					boxmins = Vector( -4.5, -4.5, 0 )
					maxs = Vector( 4.5, 4.5, 6 )
					boxmaxs = Vector( 4.5, 4.5, 50 )
					initialstate = "1"
					BlockType = "4"
					origin = Vector( 90, 40, -10 )
				}
			}
			blockpylon2 =
			{
				SpawnInfo =
				{
					classname = "env_physics_blocker"
					targetname = "Level_block"
					mins = Vector( -4.5, -4.5, 0 )
					boxmins = Vector( -4.5, -4.5, 0 )
					maxs = Vector( 4.5, 4.5, 6 )
					boxmaxs = Vector( 4.5, 4.5, 50 )
					initialstate = "1"
					BlockType = "4"
					origin = Vector( -90, -40, -10 )
				}
			}
			blockpylon3 =
			{
				SpawnInfo =
				{
					classname = "env_physics_blocker"
					targetname = "Level_block"
					mins = Vector( -4.5, -4.5, 0 )
					boxmins = Vector( -4.5, -4.5, 0 )
					maxs = Vector( 4.5, 4.5, 6 )
					boxmaxs = Vector( 4.5, 4.5, 50 )
					initialstate = "1"
					BlockType = "4"
					origin = Vector( -90, 40, -10 )
				}
			}
			blockpylon4 =
			{
				SpawnInfo =
				{
					classname = "env_physics_blocker"
					targetname = "Level_block"
					mins = Vector( -4.5, -4.5, 0 )
					boxmins = Vector( -4.5, -4.5, 0 )
					maxs = Vector( 4.5, 4.5, 6 )
					boxmaxs = Vector( 4.5, 4.5, 50 )
					initialstate = "1"
					BlockType = "4"
					origin = Vector( 90, -40, -10 )
				}
			}
			Level_navblock =
			{
				SpawnInfo =
				{
					classname = "script_nav_blocker"
					extent = Vector(30, 30, 40)
					solid = "2"
					targetname = "Level_navblock"
					origin = Vector(0, 0, -20)
					angles = Vector(0, 0, 0)
					affectsFlow = "1"
					teamToBlock = "-1"
					StartDisabled = "1"
					//RecheckBreakables = "1"
				}
			}
			Level_navblock1 =
			{
				SpawnInfo =
				{
					classname = "script_nav_blocker"
					extent = Vector(2, 2, 40)
					solid = "2"
					targetname = "Level_navblock"
					origin = Vector(90, 40, -20)
					angles = Vector(0, 0, 0)
					affectsFlow = "1"
					teamToBlock = "-1"
					StartDisabled = "1"
					//RecheckBreakables = "1"
				}
			}
			Level_navblock2 =
			{
				SpawnInfo =
				{
					classname = "script_nav_blocker"
					extent = Vector(2, 2, 40)
					solid = "2"
					targetname = "Level_navblock"
					origin = Vector(-90, -40, -20)
					angles = Vector(0, 0, 0)
					affectsFlow = "1"
					teamToBlock = "-1"
					StartDisabled = "1"
					//RecheckBreakables = "1"
				}
			}
			Level_navblock3 =
			{
				SpawnInfo =
				{
					classname = "script_nav_blocker"
					extent = Vector(2, 2, 40)
					solid = "2"
					targetname = "Level_navblock"
					origin = Vector(-90, 40, -20)
					angles = Vector(0, 0, 0)
					affectsFlow = "1"
					teamToBlock = "-1"
					StartDisabled = "1"
					//RecheckBreakables = "1"
				}
			}
			Level_navblock4 =
			{
				SpawnInfo =
				{
					classname = "script_nav_blocker"
					extent = Vector(2, 2, 40)
					solid = "2"
					targetname = "Level_navblock"
					origin = Vector(90, -40, -20)
					angles = Vector(0, 0, 0)
					affectsFlow = "1"
					teamToBlock = "-1"
					StartDisabled = "1"
					//RecheckBreakables = "1"
				}
			}
			Level_worldOut =
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					angles = Vector( 0, 0, 0 )
					origin = Vector( 0, 0, -50000 )
					model = "models/props_junk/wood_crate001a.mdl"
					targetname = "Level_worldOut"
					connections =
					{
						OnOutOfWorld =
						{
							cmd1 = "Level_navblockBlockNav0-1"
							cmd2 = "icechest_lightTurnOff00-1"
							cmd3 = "Level_worldOutKill0-1"
						}
					}
				}
			}
		} // SpawnTables
	} // EntityGroup
} // Trainladder

RegisterEntityGroup( "LvObj", LvObj )